node_user: validator
node_home: /home/validator

# Node identification
node_moniker: "{{ inventory_hostname }}"

# Directory structure (all relative to node_home)
dirs:
  root: "{{ node_home }}/chains"
  chain_home: "{{ node_home }}/chains/{{ chain.name }}_{{ chain.network }}"
  snapshot: "{{ node_home }}/snapshots"
  backup: "{{ node_home }}/backups"

# Chain binary (can be overridden)
chain_binary: "{{ chain.binary | default(chain.name + 'd') }}"

# Common Cosmos configurations
cosmos:
  min_gas_price: "0.025uusdc"
  pruning:
    mode: "custom"
    keep_recent: "100"
    keep_every: "0"
    interval: "10"
  indexer: "null"
  min_retain_blocks: 100
  state_sync:
    enabled: true
    trust_period: "168h"
    chunk_request_timeout: "10s"
    snapshot_interval: 2000

# Network configuration
network:
  # P2P configuration
  p2p_laddr: "tcp://0.0.0.0:26656"  # Listen address for p2p connections
  external_address: ""  # External address to advertise to peers
  # RPC configuration
  rpc_laddr: "tcp://0.0.0.0:26657"  # Listen address for RPC server
  grpc_laddr: "tcp://0.0.0.0:26659"  # Listen address for gRPC server (empty disables it)
  # Private validator listen port configuration
  priv_validator_listen_port: 2024  # listned port for external validator connections (empty uses local key) 