---
# User configuration
node_user: validator
node_group: validator
node_home: /home/validator
node_moniker: "{{ inventory_hostname }}"

# Common Cosmos configurations
cosmos:
  min_gas_price: "0.025uusdc"  # Default minimum gas price
  pruning:
    mode: "custom"          # default, nothing, everything, or custom
    keep_recent: "100"      # number of recent heights to keep
    keep_every: "0"         # every Nth block to keep
    interval: "10"          # blocks to wait between pruning
  indexer: "null"           # kv or null
  min_retain_blocks: 100    # minimum block retention
  state_sync:
    enabled: true
    trust_period: "168h"    # 7 days
    chunk_request_timeout: "10s"
    snapshot_interval: 2000  # blocks between trust height updates

# Directory structure
dirs:
  root: "{{ node_home }}/chains"
  chain_home: "{{ node_home }}/chains/{{ chain.name }}_{{ chain.network }}"
  snapshot: "{{ node_home }}/snapshots"
  backup: "{{ node_home }}/backups"

# Docker configuration
docker:
  ports:
    - "26656:26656"
    - "26657:26657"

# Binary configuration
chain_binary: "{{ chain.name }}d"  # Automatically append 'd' to chain name
chain_binary_path: "/go/bin/{{ chain_binary }}"  # Full path to binary 