---
# Node user configuration (from inventory)
node_user: "{{ os_users[0].name }}"  # Takes the first user from inventory
node_group: "{{ os_users[0].group }}"  # Takes the first user's group from inventory
node_home: "{{ os_users[0].home }}"   # Takes the first user's home

# Node identification
node_moniker: "{{ inventory_hostname }}"

# Directory structure (all relative to node_home)
dirs:
  root: "{{ node_home }}/chains"
  chain_home: "{{ node_home }}/chains/{{ chain.name }}_{{ chain.network }}"
  snapshot: "{{ node_home }}/snapshots"
  backup: "{{ node_home }}/backups"

# Chain binary (can be overridden)
chain_binary: "{{ chain.binary | default(chain.name + 'd') }}"

# Common Cosmos configurations
cosmos:
  min_gas_price: "0.025uusdc"
  pruning:
    mode: "custom"
    keep_recent: "100"
    keep_every: "0"
    interval: "10"
  indexer: "null"
  min_retain_blocks: 100
  state_sync:
    enabled: true
    trust_period: "168h"
    chunk_request_timeout: "10s"
    snapshot_interval: 2000 