---
# Horcrux signer configuration
horcrux:
  image: "ghcr.io/strangelove-ventures/horcrux:v3.3.1"
  state_dir: "/home/{{ node_user }}/horcrux"
  p2p_port: 2222  # Base port for Raft consensus
  public_base_port: 3000 # Base port for validator connections

# Node user and group defaults if not provided
node_user: signer
node_group: signer
node_home: /home/signer
node_uid: 1000
node_gid: 1000 