
# Horcrux signer configuration
horcrux:
  image: "ghcr.io/strangelove-ventures/horcrux:v3.3.1"
  state_dir: "/home/signer"
  p2p_port: 2222  # Base port for Raft consensus
  public_base_port: 3000 # Base port for validator connections
  threshold: 3
  total_cosigners: 5


node_home: /home/signer
