---
- name: Debug Docker Service Issues
  hosts: all
  become: true
  
  tasks:
    - name: Get Docker service status
      command: systemctl status docker
      register: docker_status
      failed_when: false
      changed_when: false

    - name: Get Docker service logs
      command: journalctl -xeu docker.service --no-pager
      register: docker_logs
      failed_when: false
      changed_when: false

    - name: Check Docker daemon configuration
      command: cat /etc/docker/daemon.json
      register: daemon_config
      failed_when: false
      changed_when: false

    - name: Display debug information
      debug:
        msg:
          - "=== Docker Status ==="
          - "{{ docker_status.stdout_lines }}"
          - "=== Docker Logs ==="
          - "{{ docker_logs.stdout_lines }}"
          - "=== Daemon Config ==="
          - "{{ daemon_config.stdout_lines }}" 