---
- name: Install Docker
  hosts: all
  become: true

  vars:
    # Docker package configuration
    docker_package: "docker-ce"
    docker_package_state: present

    # Docker compose configuration
    docker_install_compose_plugin: true
    docker_compose_package_state: present

    # Service configuration
    docker_service_state: started
    docker_service_enabled: true
    
    # Docker daemon options with basic security
    docker_daemon_options:
      storage-driver: "overlay2"
      log-driver: "json-file"
      log-opts:
        max-size: "10m"
        max-file: "3"
      live-restore: true
      userland-proxy: false
      log-level: "info"
      # Using default seccomp profile
      seccomp-profile: "/etc/docker/default-seccomp.json"

    # Docker users to be added to docker group
    docker_users:
      - "{{ ansible_user }}"
      - "validator"
      - "signer"

  pre_tasks:
    - name: Ensure Docker directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - /etc/docker

    - name: Download default Docker seccomp profile
      get_url:
        url: https://raw.githubusercontent.com/docker/engine/master/profiles/seccomp/default.json
        dest: /etc/docker/default-seccomp.json
        mode: '0644'
        force: no

    - name: Stop Docker service if running
      systemd:
        name: docker
        state: stopped
      failed_when: false

  roles:
    - geerlingguy.docker

  post_tasks:
    - name: Verify Docker service status
      systemd:
        name: docker
        state: started
      register: docker_service
      
    - name: Show Docker service status
      debug:
        var: docker_service
