---
- name: Setup Base System Configuration
  hosts: all
  become: true
  roles:
    - role: devsec.hardening.ssh_hardening
    - role: devsec.hardening.os_hardening
      vars:
        manage_users: true
        manage_groups: true
        sysctl_overwrite:
          # Enable IPv4 traffic forwarding for Docker
          net.ipv4.ip_forward: 1
    - role: geerlingguy.docker
      vars:
        docker_install_compose_plugin: true
