---
# Main playbook that depends on users being created
- name: Setup Validator Node
  hosts: noble-fullnode-testnet
  become: true
  roles:
    - role: ../roles/cosmos_common 
    # - role: ../roles/cosmos_snapshot

- name: Setup Signer Node
  hosts: signers
  become: true
  roles:
    - role: ../roles/cosmos_signer 